/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.seeds;

import Classes.EntradaCaixa;
import Classes.LimitadorMoeda;
import ClassesDAO.CaixaDAO;
import ClassesDAO.SubProdutosDAO;
import Excessoes.BancoException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import seeds.Main;

/**
 *
 * @author Guilherme
 */
public class CaixaEntrada extends javax.swing.JFrame {

    /**
     * Creates new form CaixaEntrada
     */
    String s, f;
    EntradaCaixa SetandoEntrada = new EntradaCaixa();
    CaixaDAO dao;

    public CaixaEntrada(int Codigo) throws BancoException, SQLException {
        initComponents();
        setLocationRelativeTo(null);
        jCheckBox2.setSelected(true);
        dao = new CaixaDAO();
        jPanel5.setVisible(false);
        //jPanel3.setVisible(false);
        jTextField8.setDocument(new OnlyNumberField(6));
        jTextField7.setDocument(new OnlyNumberField(6));
        jTextField6.setDocument(new LimitadorMoeda());
        jTextField2.setDocument(new LimitadorMoeda());
        jTextField1.setDocument(new FixedLengthDocumentx(49));
        if (Codigo > 0) {
            SubProdutosDAO Sub = new SubProdutosDAO();
            ResultSet SubP = Sub.SelecionandoSubprodutos(Codigo);

            while (SubP.next()) {
                jCheckBox1.setSelected(true);
                jTextField5.setText(SubP.getString("Nome"));
                jTextField6.setText(SubP.getString("PrecoVenda").replace(".", "").replace(",", ""));
                jTextField8.setText("" + Codigo);
                jTextField7.requestFocus();
            }
            jTextField7.requestFocus();
        }
        NowString();
    }

    public void NowString() {
        Date now = new Date();
        DateFormat df = DateFormat.getDateInstance();
        DateFormat dg = DateFormat.getTimeInstance();
        s = df.format(now);
        f = dg.format(now);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Suprimento");
        setResizable(false);

        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel1.setText(" Descrição:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setText(" Valor:");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 406, Short.MAX_VALUE))
                    .addComponent(jTextField1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel3});

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 30, 620, 90);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel6.setText("* Produto: ");

        jTextField5.setEditable(false);
        jTextField5.setFocusable(false);

        jLabel7.setText("* Valor:");

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });

        jLabel8.setText("* Quantidade:");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imagens/buscar.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });

        jLabel9.setText("* Código do produto:");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imagens/entrar.png"))); // NOI18N
        jButton6.setText("Finalizar");
        jButton6.setToolTipText("Concluir um pagamento e Inativar o funcionário");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6KeyPressed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imagens/cancelar.png"))); // NOI18N
        jButton7.setText("Sair");
        jButton7.setToolTipText("Fechará a tela funcionários e voltará ao menu principal");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel6, jLabel7, jLabel8});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jTextField5)
                        .addComponent(jLabel6))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel6, jLabel7, jLabel8});

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 30, 500, 90);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Simples");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jCheckBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckBox2KeyPressed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setText("Venda de produto");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jCheckBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckBox1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(190, 30, 10, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel12.setText("* Campos obrigatórios!");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 129, 11);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imagens/entrar.png"))); // NOI18N
        jButton2.setText("Finalizar");
        jButton2.setToolTipText("Concluir um pagamento e Inativar o funcionário");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 140, 138, 48);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imagens/cancelar.png"))); // NOI18N
        jButton4.setText("Sair");
        jButton4.setToolTipText("Fechará a tela funcionários e voltará ao menu principal");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(160, 140, 138, 48);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-656)/2, (screenSize.height-239)/2, 656, 239);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Clicou em Finalizar

        if (jCheckBox2.isSelected()) {

            if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "O campo Descrição precisa ser preenchido!");
                jTextField1.requestFocus();
            } else if (jTextField2.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "O campo Valor precisa ser preenchido!");
                jTextField2.requestFocus();
            } else {
                NowString();
                int CodigoAbertura = 0;



                try {
                    ResultSet Verificando = dao.VerificaAbertura(s, f);
                    while (Verificando.next()) {
                        CodigoAbertura = Verificando.getInt("Codigo");
                    }
                    Verificando.close();

                } catch (SQLException ex) {
                    Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                }


                SetandoEntrada.setSimples(true);
                SetandoEntrada.setQuantidade(1);
                String Valor = jTextField2.getText();
                Valor = Valor.replace(".", "");
                Valor = Valor.replace(",", ".");
                SetandoEntrada.setValor(Float.parseFloat(Valor));
                SetandoEntrada.setData(s);
                SetandoEntrada.setHora(f);
                SetandoEntrada.setOperacao(jTextField1.getText());
                SetandoEntrada.setCodigoAbertura(CodigoAbertura);

                try {
                    dao.InserindoEntradaSimples(SetandoEntrada);
                } catch (BancoException ex) {
                    Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                }



                JOptionPane.showMessageDialog(this, "Sucesso!");
                this.dispose();
                try {
                    try {
                        Main.Caixa.AoIniciar();
                    } catch (BancoException ex) {
                        Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                }
                Main.Caixa.setVisible(true);
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Clicou em sair
        this.dispose();
        try {
            try {
                Main.Caixa.AoIniciar();
            } catch (BancoException ex) {
                Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ParseException ex) {
            Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
        }
        Main.Caixa.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // Clicou lupa
            BuscarSubprodutosCaixa Busca = new BuscarSubprodutosCaixa();
            Busca.setVisible(true);
            this.dispose();
        } catch (BancoException ex) {
            Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Clicou em finalizar
        if (jCheckBox1.isSelected()) {

            if (jTextField8.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "O campo Código do produto precisa ser preenchido!");
                jTextField8.requestFocus();
            } else if (jTextField6.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "O campo Valor precisa ser preenchido!");
                jTextField6.requestFocus();
            } else if (jTextField7.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "O campo Quantidade precisa ser preenchido!");
                jTextField7.requestFocus();
            } else if (jTextField5.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Produto não informado!");

            } else {
                NowString();
                int CodigoAbertura = 0;
                int Quantidade = 0;
                boolean Continuar = false;
                boolean Subtrair = false;

                try {
                    ResultSet Verificando = dao.VerificaAbertura(s, f);
                    while (Verificando.next()) {
                        CodigoAbertura = Verificando.getInt("Codigo");
                    }
                    Verificando.close();
                    ResultSet Verificando1 = dao.SelecionandoEstoque(Integer.parseInt(jTextField8.getText()));

                    while (Verificando1.next()) {
                        Quantidade = Verificando1.getInt("Quantidade");
                        Subtrair = true;
                    }

                    Verificando1.close();

                    if (Quantidade >= Integer.parseInt(jTextField7.getText()) && Subtrair) {
                        dao.SubtraindoEstoque(Integer.parseInt(jTextField8.getText()), Integer.parseInt(jTextField7.getText()));
                        Continuar = true;
                    } else if (Subtrair) {
                        JOptionPane.showMessageDialog(this, "A quantidade em estoque é menor que a informada!");
                    } else {
                        Continuar = true;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                } catch (BancoException ex) {
                    Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (Continuar) {
                    SetandoEntrada.setCodigoProduto(Integer.parseInt(jTextField8.getText()));
                    SetandoEntrada.setSimples(false);
                    SetandoEntrada.setProduto(jTextField5.getText());
                    SetandoEntrada.setQuantidade(Integer.parseInt(jTextField7.getText()));
                    String Valor = jTextField6.getText();
                    Valor = Valor.replace(".", "");
                    Valor = Valor.replace(",", ".");
                    SetandoEntrada.setValor(Float.parseFloat(Valor));
                    SetandoEntrada.setData(s);
                    SetandoEntrada.setHora(f);
                    SetandoEntrada.setOperacao("Venda");
                    SetandoEntrada.setCodigoAbertura(CodigoAbertura);

                    try {
                        dao.InserindoEntrada(SetandoEntrada);

                    } catch (BancoException ex) {
                        Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                    }



                    JOptionPane.showMessageDialog(this, "Sucesso!");
                    this.dispose();
                    try {
                        try {
                            Main.Caixa.AoIniciar();
                        } catch (BancoException ex) {
                            Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (SQLException ex) {
                            Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (ParseException ex) {
                        Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Main.Caixa.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Sair
        this.dispose();
        try {
            try {
                Main.Caixa.AoIniciar();
            } catch (BancoException ex) {
                Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ParseException ex) {
            Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
        }
        Main.Caixa.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // Clicou em Simples
        if (jCheckBox2.isSelected()) {
            jPanel5.setVisible(false);
            jPanel3.setVisible(true);
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // Clicou em venda de produto
        if (jCheckBox1.isSelected()) {
            jPanel5.setVisible(true);
            jPanel3.setVisible(false);
            jTextField8.requestFocus();
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost
        // Saiu Codigo
    }//GEN-LAST:event_jTextField8FocusLost

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        // clicou enter em codigo
        int co = evt.getKeyCode();

        if (co == 10) {
            boolean Achou = false;
            try {
                ResultSet PuxandoProduto = dao.SelecionandoSubProdutos(Integer.parseInt(jTextField8.getText()));

                while (PuxandoProduto.next()) {
                    jTextField5.setText(PuxandoProduto.getString("Nome"));
                    String ValorTotal = new DecimalFormat("0.00").format((PuxandoProduto.getFloat("PrecoVenda")));
                    ValorTotal = ValorTotal.replace(".", "");
                    ValorTotal = ValorTotal.replace(",", "");
                    jTextField6.setText(ValorTotal);
                    jTextField7.requestFocus();
                    Achou = true;
                }
                PuxandoProduto.close();

                if (!Achou) {
                    JOptionPane.showMessageDialog(this, "Produto não encontrado!");
                }
            } catch (BancoException ex) {
                Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // apertou enter
        int Apertou = evt.getKeyCode();
        if (Apertou == 10) {
            jButton6.requestFocus();
        }
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
        // Clicou enter Finalizar
        int Apertou = evt.getKeyCode();
        if (Apertou == 10) {
            if (jCheckBox1.isSelected()) {

                if (jCheckBox1.isSelected()) {

                    if (jTextField8.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "O campo Código do produto precisa ser preenchido!");
                        jTextField8.requestFocus();
                    } else if (jTextField6.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "O campo Valor precisa ser preenchido!");
                        jTextField6.requestFocus();
                    } else if (jTextField7.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "O campo Quantidade precisa ser preenchido!");
                        jTextField7.requestFocus();
                    } else if (jTextField5.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Produto não informado!");

                    } else {
                        NowString();
                        int CodigoAbertura = 0;
                        int Quantidade = 0;
                        boolean Continuar = false;
                        boolean Subtrair = false;

                        try {
                            ResultSet Verificando = dao.VerificaAbertura(s, f);
                            while (Verificando.next()) {
                                CodigoAbertura = Verificando.getInt("Codigo");
                            }
                            Verificando.close();
                            ResultSet Verificando1 = dao.SelecionandoEstoque(Integer.parseInt(jTextField8.getText()));

                            while (Verificando1.next()) {
                                Quantidade = Verificando1.getInt("Quantidade");
                                Subtrair = true;
                            }

                            Verificando1.close();

                            if (Quantidade >= Integer.parseInt(jTextField7.getText()) && Subtrair) {
                                dao.SubtraindoEstoque(Integer.parseInt(jTextField8.getText()), Integer.parseInt(jTextField7.getText()));
                                Continuar = true;
                            } else if (Subtrair) {
                                JOptionPane.showMessageDialog(this, "A quantidade em estoque é menor que a informada!");
                            } else {
                                Continuar = true;
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (BancoException ex) {
                            Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (ParseException ex) {
                            Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        if (Continuar) {
                            SetandoEntrada.setCodigoProduto(Integer.parseInt(jTextField8.getText()));
                            SetandoEntrada.setSimples(false);
                            SetandoEntrada.setProduto(jTextField5.getText());
                            SetandoEntrada.setQuantidade(Integer.parseInt(jTextField7.getText()));
                            String Valor = jTextField6.getText();
                            Valor = Valor.replace(".", "");
                            Valor = Valor.replace(",", ".");
                            SetandoEntrada.setValor(Float.parseFloat(Valor));
                            SetandoEntrada.setData(s);
                            SetandoEntrada.setHora(f);
                            SetandoEntrada.setOperacao("Venda");
                            SetandoEntrada.setCodigoAbertura(CodigoAbertura);

                            try {
                                dao.InserindoEntrada(SetandoEntrada);

                            } catch (BancoException ex) {
                                Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                            }



                            JOptionPane.showMessageDialog(this, "Sucesso!");
                            this.dispose();
                            try {
                                try {
                                    Main.Caixa.AoIniciar();
                                } catch (BancoException ex) {
                                    Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (SQLException ex) {
                                    Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            } catch (ParseException ex) {
                                Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            Main.Caixa.setVisible(true);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton6KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Clicou em Finalizar

            if (jCheckBox2.isSelected()) {

                if (jTextField1.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "O campo Descrição precisa ser preenchido!");
                    jTextField1.requestFocus();
                } else if (jTextField2.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "O campo Valor precisa ser preenchido!");
                    jTextField2.requestFocus();
                } else {
                    NowString();
                    int CodigoAbertura = 0;



                    try {
                        ResultSet Verificando = dao.VerificaAbertura(s, f);
                        while (Verificando.next()) {
                            CodigoAbertura = Verificando.getInt("Codigo");
                        }
                        Verificando.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ParseException ex) {
                        Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                    }


                    SetandoEntrada.setSimples(true);
                    SetandoEntrada.setQuantidade(1);
                    String Valor = jTextField2.getText();
                    Valor = Valor.replace(".", "");
                    Valor = Valor.replace(",", ".");
                    SetandoEntrada.setValor(Float.parseFloat(Valor));
                    SetandoEntrada.setData(s);
                    SetandoEntrada.setHora(f);
                    SetandoEntrada.setOperacao(jTextField1.getText());
                    SetandoEntrada.setCodigoAbertura(CodigoAbertura);

                    try {
                        dao.InserindoEntradaSimples(SetandoEntrada);
                    } catch (BancoException ex) {
                        Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                    }



                    JOptionPane.showMessageDialog(this, "Sucesso!");
                    this.dispose();
                    try {
                        try {
                            Main.Caixa.AoIniciar();
                        } catch (BancoException ex) {
                            Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (SQLException ex) {
                            Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (ParseException ex) {
                        Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Main.Caixa.setVisible(true);
                }

            }
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // apetar enter em finalizar simples
        int evento;

        evento = evt.getKeyCode();
        if (evento == 10) {
            if (jCheckBox2.isSelected()) {

                if (jTextField1.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "O campo Descrição precisa ser preenchido!");
                    jTextField1.requestFocus();
                } else if (jTextField2.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "O campo Valor precisa ser preenchido!");
                    jTextField2.requestFocus();
                } else {
                    NowString();
                    int CodigoAbertura = 90;



                    try {
                        ResultSet Verificando = dao.VerificaAbertura(s, f);
                        while (Verificando.next()) {
                            CodigoAbertura = Verificando.getInt("Codigo");
                        }
                        Verificando.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ParseException ex) {
                        Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                    }


                    SetandoEntrada.setSimples(true);
                    SetandoEntrada.setQuantidade(1);
                    String Valor = jTextField2.getText();
                    Valor = Valor.replace(".", "");
                    Valor = Valor.replace(",", ".");
                    SetandoEntrada.setValor(Float.parseFloat(Valor));
                    SetandoEntrada.setData(s);
                    SetandoEntrada.setHora(f);
                    SetandoEntrada.setOperacao(jTextField1.getText());
                    SetandoEntrada.setCodigoAbertura(CodigoAbertura);

                    try {
                        dao.InserindoEntradaSimples(SetandoEntrada);
                    } catch (BancoException ex) {
                        Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                    }



                    JOptionPane.showMessageDialog(this, "Sucesso!");
                    this.dispose();
                    try {
                        try {
                            Main.Caixa.AoIniciar();
                        } catch (BancoException ex) {
                            Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (SQLException ex) {
                            Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (ParseException ex) {
                        Logger.getLogger(CaixaEntrada.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Main.Caixa.setVisible(true);
                }

            }
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jCheckBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox2KeyPressed
        // pressionou enter em simples
        int evento;

        evento = evt.getKeyCode();
        if (evento == 10) {
            jCheckBox2.setSelected(true);
            jCheckBox1.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox2KeyPressed

    private void jCheckBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox1KeyPressed
        // enter em venda 
        int evento;

        evento = evt.getKeyCode();
        if (evento == 10) {
            jCheckBox2.setSelected(false);
            jCheckBox1.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox1KeyPressed

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        // TODO add your handling code here:
        if (jCheckBox2.isSelected()) {
            jPanel5.setVisible(false);
            jPanel3.setVisible(true);
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            jPanel5.setVisible(true);
            jPanel3.setVisible(false);
            jTextField8.requestFocus();
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
